#!/usr/bin/env bash
#Script to configure Heroku C buildpack to install JDK

# download the JVM buildpack
JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz}
mkdir -p /tmp/jvm-common
curl --silent --location $JVM_COMMON_BUILDPACK | tar xzm -C /tmp/jvm-common --strip-components=1
. /tmp/jvm-common/bin/util
. /tmp/jvm-common/bin/java

# install JDK
javaVersion=$(detect_java_version ${BUILD_DIR})
install_java ${BUILD_DIR} ${javaVersion}

# install python 3
mkdir ~/work/python
wget http://projects.joelinoff.com/pybld/pybld.sh
chmod a+x pybld.sh
./pybld.sh -v 3.4.3 -b 3.4.3/bld -r 3.4.3
python --version

# install fbuild
git clone https://github.com/felix-lang/fbuild.git
python fbuild/setup.py install
