/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_jadonfowler_o_OCBindings */

#ifndef _Included_xyz_jadonfowler_o_OCBindings
#define _Included_xyz_jadonfowler_o_OCBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_jadonfowler_o_OCBindings
 * Method:    parse
 * Signature: (Ljava/lang/Character;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_jadonfowler_o_OCBindings_parse
  (JNIEnv *, jobject, jobject);

/*
 * Class:     xyz_jadonfowler_o_OCBindings
 * Method:    cl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_jadonfowler_o_OCBindings_cl
  (JNIEnv *, jobject);

/*
 * Class:     xyz_jadonfowler_o_OCBindings
 * Method:    setInputs
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xyz_jadonfowler_o_OCBindings_setInputs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     xyz_jadonfowler_o_OCBindings
 * Method:    setInputPointer
 * Signature: (Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_xyz_jadonfowler_o_OCBindings_setInputPointer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     xyz_jadonfowler_o_OCBindings
 * Method:    getCurrentStackContents
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_jadonfowler_o_OCBindings_getCurrentStackContents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
